config/routes.rb
Rails.application.routes.draw do


  devise_for :users
#  resources :users
  resources :movies do 
  resources :movie_genres  do 
    member { post :vote }
  resources :movie_genre_comments, shallow: true do
    member { post :vote }
      end
    end
  resources :movie_themes do 
    member { post :vote }
  resources :movie_theme_comments, shallow: true do
    member { post :vote }
  end
end
    
      resources :movie_locations do 
    member { post :vote }
  resources :movie_location_comments, shallow: true do
    member { post :vote }
            
    end
  end


resources :movie_characters do 
    member { post :vote }
  resources :movie_character_comments, shallow: true do
    member { post :vote }
  end
end
    
resources :movie_brands do 
    member { post :vote }
  resources :movie_brand_comments, shallow: true do
    member { post :vote }
            
    end
  end

resources :movie_goofs do 
    member { post :vote }
  resources :movie_goof_comments, shallow: true do
    member { post :vote }
  end
end
    
resources :movie_references do 
    member { post :vote }
  resources :movie_reference_comments, shallow: true do
    member { post :vote }
  end
end

resources :movie_songs do 
    member { post :vote }
  resources :movie_song_comments, shallow: true do
    member { post :vote }
  end
end
resources :movie_technicals do 
    member { post :vote }
  resources :movie_technical_comments, shallow: true do
    member { post :vote }
  end
end

resources :movie_quotes do 
    member { post :vote }
  resources :movie_quote_comments, shallow: true do
    member { post :vote }
  end
end
      
      
end

   
  get 'search', to: 'search#search'

  
   root 'movies#index'


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @movies = Movie.all
  end


  def show
    @movie_genres = MovieGenre.where(movie_id: @movie.id)
    @movie_themes = MovieTheme.where(movie_id: @movie.id)
    @movie_locations = MovieLocation.where(movie_id: @movie.id)
    @movie_characters = MovieCharacter.where(movie_id: @movie.id)
    @movie_brands = MovieBrand.where(movie_id: @movie.id)
    @movie_goofs = MovieGoof.where(movie_id: @movie.id)
    @movie_references = MovieReference.where(movie_id: @movie.id)
    @movie_songs = MovieSong.where(movie_id: @movie.id)
    @movie_technicals = MovieTechnical.where(movie_id: @movie.id)
    @movie_quotes = MovieQuote.where(movie_id: @movie.id)
   # @movie_genre = MovieGenre.find(params[:movie_id])

  end


  def new
     @movie = current_user.movies.build
  end


  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
       params.require(:movie).permit(:title, :description, :movie_length, :poster)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :movie_length %><br>
    <%= f.text_field :movie_length %>
  </div>
  <div class="field">
     <%= f.label :poster %><br>
     <%= f.file_field :poster %>
  </div>
  <div class="actions", class: "btn btn-primary">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_linker.html.erb
  <div class="panel panel-default">
    <div class="container">
      <div class="container-fluid">
        <tbody>
          <table class="table">
                      <div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <strong>Add More</strong><span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "Add Genre", new_movie_movie_genre_path(@movie) %></li>
    <li><%= link_to "Add Location", new_movie_movie_location_path(@movie) %></li>
    <li><%= link_to "Add Theme", new_movie_movie_theme_path(@movie) %></li>
    <li><%= link_to "Add Brand", new_movie_movie_brand_path(@movie) %></li>
    <li><%= link_to "Add Character", new_movie_movie_character_path(@movie) %></li>
    <li><%= link_to "Add Goof", new_movie_movie_goof_path(@movie) %></li>
    <li><%= link_to "Add Reference", new_movie_movie_reference_path(@movie) %></li>
    <li><%= link_to "Add Song", new_movie_movie_song_path(@movie) %></li>
    <li><%= link_to "Add Technical", new_movie_movie_technical_path(@movie) %></li>
    <li><%= link_to "Add Quote", new_movie_movie_quote_path(@movie) %></li>
    <li class="divider"></li>
    <li><a href="#">Some crap here</a></li>
  </ul>
</div>
         <tr>
         <div class="col-md-12"><h3>Genres</strong></h3>


       <% @movie_genres.popular.each do |movie_genre| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_genre.title, movie_movie_genre_path(@movie, movie_genre), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_genre.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_genre_path(@movie, movie_genre,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_genre_path(@movie, movie_genre,  type: "down"), method: "post" %></div>
                 <% end %>
                   </tr>
                   <tr>
                   <div class="col-md-12"><h3>Themes</strong></h3>
                    <td>
          <% @movie_themes.popular.each do |movie_theme| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_theme.title, movie_movie_theme_path(@movie, movie_theme), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_theme.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_theme_path(@movie, movie_theme,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_theme_path(@movie, movie_theme,  type: "down"), method: "post" %></div>
                 <% end %>

                </tr>
                   <tr>
                  
                    <td>
                       <div class="col-md-12"><h3>Locations</strong></h3>
                    <% @movie_locations.popular.each do |movie_location| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_location.title, movie_movie_location_path(@movie, movie_location), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_location.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_location_path(@movie, movie_location,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_location_path(@movie, movie_location,  type: "down"), method: "post" %></div>
                 <% end %>
                  </tr>
                  </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Characters</strong></h3>
          <% @movie_characters.popular.each do |movie_character| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_character.name, movie_movie_character_path(@movie, movie_character), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_character.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_character_path(@movie, movie_character,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_character_path(@movie, movie_character,  type: "down"), method: "post" %></div>
                 <% end %>
                  </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Brands</strong></h3>
          <% @movie_brands.popular.each do |movie_brand| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_brand.title, movie_movie_brand_path(@movie, movie_brand), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_brand.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_brand_path(@movie, movie_brand,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_brand_path(@movie, movie_brand,  type: "down"), method: "post" %></div>
                 <% end %>
              
                  </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Goofs</strong></h3>
                    <% @movie_goofs.popular.each do |movie_goof| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_goof.title, movie_movie_goof_path(@movie, movie_goof), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_goof.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_goof_path(@movie, movie_goof,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_goof_path(@movie, movie_goof,  type: "down"), method: "post" %></div>
                 <% end %>
                                                  </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>References</strong></h3>
          <% @movie_references.popular.each do |movie_reference| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_reference.title, movie_movie_reference_path(@movie, movie_reference), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_reference.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_reference_path(@movie, movie_reference,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_reference_path(@movie, movie_reference,  type: "down"), method: "post" %></div>
                 <% end %>
                      
                                        </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Songs</strong></h3>
            
                    <% @movie_songs.popular.each do |movie_song| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_song.title, movie_movie_song_path(@movie, movie_song), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_song.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_song_path(@movie, movie_song,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_song_path(@movie, movie_song,  type: "down"), method: "post" %></div>
                 <% end %>
                                        </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Technical</strong></h3>
          
          <% @movie_technicals.popular.each do |movie_technical| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_technical.title, movie_movie_technical_path(@movie, movie_technical), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_technical.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_technical_path(@movie, movie_technical,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_technical_path(@movie, movie_technical,  type: "down"), method: "post" %></div>
                 <% end %>
                                        </tr>
        </td>
                   <tr>
                   
                    <td>
<div class="col-md-12"><h3>Quotes</strong></h3>
            
          <% @movie_quotes.popular.each do |movie_quote| %>
               <div class="col-md-4">  <h3><span class="label label-default"><strong><%= link_to movie_quote.title, movie_movie_quote_path(@movie, movie_quote), class: 'linkers-class' %></h3></strong><strong><span class="badge"><%= pluralize movie_quote.reputation_for(:votes).to_i, "" %></strong></span></span>
                 <%= link_to "up", vote_movie_movie_quote_path(@movie, movie_quote,  type: "up"), method: "post" %>  <%= link_to "down", vote_movie_movie_quote_path(@movie, movie_quote,  type: "down"), method: "post" %></div>
                 <% end %>

          </table>
       </tbody>
    </div>
  </div>
</div>

          

        </div>
    </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Explore Movies In A New Way</h1>
    <p>Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cardigan. Organic drinking vinegar freegan pickled.</p>
    <p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
         <%= link_to (image_tag movie.poster.url(:medium), class: 'image'), movie %>
         <td><strong><%= movie.title %></strong></td>
      </div>
    </div>
    
  <% end %>
</div>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="panel panel-default">
<div class="container">
  <div class="row">
    <div class="col-md-4"><%= image_tag @movie.poster.url(:medium) %>
    </div>
    
    <div class="col-md-8">  <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Movie length:</strong></td>
                <td><%= @movie.movie_length %></td>
              </tr>
              <tr>
                <td><strong>User:</strong></td>
                <td><%= @movie.user.email %></td>
              </tr>
            
               
               <tr>
 
    
               </tr>
              
            </tbody>
          </table>
     
      </div>
        </div>
    </div>
  </div>
</div>

   <%= render 'linker' %>

<%= link_to 'Edit', edit_movie_path(@movie) %> |